/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const ReportLazyImport = createFileRoute('/report')()
const RemoveLazyImport = createFileRoute('/remove')()
const ManualLazyImport = createFileRoute('/manual')()
const CelluloseLazyImport = createFileRoute('/cellulose')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const ReportLazyRoute = ReportLazyImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/report.lazy').then((d) => d.Route))

const RemoveLazyRoute = RemoveLazyImport.update({
  id: '/remove',
  path: '/remove',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/remove.lazy').then((d) => d.Route))

const ManualLazyRoute = ManualLazyImport.update({
  id: '/manual',
  path: '/manual',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/manual.lazy').then((d) => d.Route))

const CelluloseLazyRoute = CelluloseLazyImport.update({
  id: '/cellulose',
  path: '/cellulose',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/cellulose.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/cellulose': {
      id: '/cellulose'
      path: '/cellulose'
      fullPath: '/cellulose'
      preLoaderRoute: typeof CelluloseLazyImport
      parentRoute: typeof rootRoute
    }
    '/manual': {
      id: '/manual'
      path: '/manual'
      fullPath: '/manual'
      preLoaderRoute: typeof ManualLazyImport
      parentRoute: typeof rootRoute
    }
    '/remove': {
      id: '/remove'
      path: '/remove'
      fullPath: '/remove'
      preLoaderRoute: typeof RemoveLazyImport
      parentRoute: typeof rootRoute
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/cellulose': typeof CelluloseLazyRoute
  '/manual': typeof ManualLazyRoute
  '/remove': typeof RemoveLazyRoute
  '/report': typeof ReportLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/cellulose': typeof CelluloseLazyRoute
  '/manual': typeof ManualLazyRoute
  '/remove': typeof RemoveLazyRoute
  '/report': typeof ReportLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/cellulose': typeof CelluloseLazyRoute
  '/manual': typeof ManualLazyRoute
  '/remove': typeof RemoveLazyRoute
  '/report': typeof ReportLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cellulose' | '/manual' | '/remove' | '/report'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cellulose' | '/manual' | '/remove' | '/report'
  id: '__root__' | '/' | '/cellulose' | '/manual' | '/remove' | '/report'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  CelluloseLazyRoute: typeof CelluloseLazyRoute
  ManualLazyRoute: typeof ManualLazyRoute
  RemoveLazyRoute: typeof RemoveLazyRoute
  ReportLazyRoute: typeof ReportLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  CelluloseLazyRoute: CelluloseLazyRoute,
  ManualLazyRoute: ManualLazyRoute,
  RemoveLazyRoute: RemoveLazyRoute,
  ReportLazyRoute: ReportLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/cellulose",
        "/manual",
        "/remove",
        "/report"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/cellulose": {
      "filePath": "cellulose.lazy.tsx"
    },
    "/manual": {
      "filePath": "manual.lazy.tsx"
    },
    "/remove": {
      "filePath": "remove.lazy.tsx"
    },
    "/report": {
      "filePath": "report.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
